url: https://jmunroe.github.io
baseurl: /

# Site settings
title: Munroe Lab
email: jmunroe@mun.ca
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: James Munroe
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: github
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/JamesMunroeNL
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jmunroe
  - title: github
    url: http://github.com/jmunroe

# Postal address (add as many lines as necessary)
address:
  - line: St. John's, NL


# Build settings
markdown: kramdown
permalink: pretty
